### ISSUE TITLE
Serve shortened URLs from godbolt.org

### ISSUE THREAD

**Issue by malcolmr** [mattgodbolt/gcc-explorer#113]
Stack Overflow has banned goo.gl links, making it [hard to post links to GCC explorer](http://meta.stackoverflow.com/questions/319549/how-are-we-supposed-to-post-godbolt-links-now-that-url-shortening-is-blocked).

One solution to this would be to implement a URL shortener on godbolt.org directly, so that permalinks would be of the form gcc.godbolt.org/s/1234 (etc). However, that requires state.

Here's an alternate proposal:

1. Use Google's URL shortener as before, but rewrite the resulting URL from http://goo.gl/F02h38 to http://gcc.godbolt.org/s/F02h38 (say).
2. Implement a handler for `/s/*` that [expands the URL server-side](https://developers.google.com/url-shortener/v1/getting_started#expand) (GET https://www.googleapis.com/urlshortener/v1/url?shortUrl=http://goo.gl/F02h38&key=..., more documentation [here](https://developers.google.com/url-shortener/v1/url/get#request)) and verifies that the `longUrl` points to godbolt.org.
3. Serve a 301 to the goo.gl URL (or a 404 if the shortened URL is invalid for any reason).

(In step 3, you could also serve a 301 to the location you already have, but bouncing through goo.gl shouldn't be too bad for latency, and allows you to retain analytics; see e.g. http://goo.gl/F02h38+. I'd also find it a bit sketchy to just use goo.gl for storage.)

This should be acceptable to Stack Overflow, since the shortened URLs can only be used on the domain they already live on.

See also #112, though I think that's asking for something else.

**Comment by pcordes** [comment]
Is there any way to make the goo.gl server see the URL-expanding request from godbolt.org as coming from the original client through a proxy?  If so, then analytics still work, and we can redirect directly to the expanded URL.

This would be a viable workaround for SO comments until SO does something to allow full URLs in comments.

Long-term, it's better to have the full data encoded in the URL.  I've had a goo.gl link go bad in one of my answers, so it's not bulletproof even without any sites disappearing / changing.  So for SO posts, it's better to use full URLs.

**Comment by malcolmr** [comment]
(I thought the full data _was_ encoded in the URL already, but that's an orthogonal problem.)

I'm not aware of any simple way to properly proxy the request short of actually emulating an HTTP proxy (and note that a request to the API doesn't trigger a hit, so you'd still need a second request to actually register the hit).

I also see there's some progress on #19, which may make this moot.

**Comment by pcordes** [comment]
The full data is encoded in the full URL, but not in a shortened URL.  If you have the full URL, you can map it into source code and compiler options even if goo.gl and godbolt.org are both inaccessible.  See Shog9's post on my SO thread.

Proxies make upstream requests just by [adding an HTTP header to the request](https://en.wikipedia.org/wiki/X-Forwarded-For).  So instead of making an API request, just send a normal GET request to the goo.gl server with an extra header, and look at the resulting redirect.  This gives you the actual hit for analytics, hopefully attributed to the forwarded-for IP rather than godbolt's own.  As long as rate-limiting doesn't block this, it seems like the ideal way to implement your idea.

(Actually getting  this to happen in whatever language godbolt's server side stuff is written in might be interesting; I haven't looked at the code.)

**Comment by malcolmr** [comment]
I think we'd still want the initial API request so that we don't accumulate hits for non-godbolt.org goo.gl links (which we'll need to 404).

For proxying: we'd also want to forward User-Agent, and perhaps other headers. It _might_ be that easy, but I'd rather just return a 301 to goo.gl for now, since that'll definitely work.

**Comment by mattgodbolt** [comment]
Another thought to keep it client-side: make URLs in step 1 of the form
gcc.godbolt.org/#s=1234abcde; then steps 2 gets done on the client (and
doesn't need a redirect). Basically similar to the gist approach, but using
google's URL shortener as a storage system.

**Comment by malcolmr** [comment]
That works too, so long as you actually turn around and fetch the goo.gl link itself (to bump analytics); as I said, I'm not too sure whether it's a good idea to use the URL shortener API just for storage, and not actually follow the links.

I think it'd also be nice to be able to follow the redirect chain with an HTTP client, but godbolt.org already requires a Javascript-enabled browser, so that's probably okay.

**Comment by mattgodbolt** [comment]
Naïve question: Why is the analytics bump important? To keep them live? I
guess it's easy enough to implement the followingness on the server anyway.
Will probably implement as you initially suggested Malcolm: thanks!

**Comment by pcordes** [comment]
re: analytics: I hadn't even realized that goo.gl links had analytics (by adding a + to the URL) until someone mentioned it on my SO post.  Now that I know that, I'm a little curious how many people have followed the godbolt.org links in my SO answers.

It seems reasonable to not break analytics for godbolt.org links if it's easy to avoid.  However, I don't know why we'd want to avoid counting as a hit for non-godbolt goo.gl links.  @malcolmr: Is there any way this is exploitable for any kind of gain, which could lead to extra traffic on godbolt from people using it as a proxy to bump their counters?

@matt: Is your client-side suggestion to have the client use the API?  The client has to avoid following non-godbolt.org links.

**Comment by malcolmr** [comment]
@pcordes I'm not sure, but since we'll have to reject the request somehow, it seemed easiest to avoid the possibility.

(and btw, if we _do_ do it client-side, we'll need to work out what happens when someone hits e.g. http://gcc.godbolt.org/#s=l6MS, which is a valid non-godbolt.org goo.gl URL. Server side is easy: we just 404 the request.)

**Comment by mattgodbolt** [comment]
As per email chat with @malcolmr, we should use 301 and Cache-Control:
public too

**Comment by mattgodbolt** [comment]
@pcordes I think the server should do all the checks; as @malcolmr suggested. I'll have a crack at this tonight.

**Comment by pcordes** [comment]
Re: link expiry: [google says links don't expire](https://support.google.com/faqs/answer/190768?hl=en) for lack of use, only for spam/privacy/legal reasons.

**Comment by mattgodbolt** [comment]
Thanks; I didn't think they expired (which is one reason I picked them). For analytics I'm still not quite sure what I'll need: is your concern that the bounce via godbolt.org/a/1234abcd will lose the original referring URL? I'll sketch something and we can see how it goes anyway!

**Comment by pcordes** [comment]
I don't care about analytics personally, it just seems like it's worth getting this right if it can be done without added latency, since @malcolmr mentioned it.  I'd rather post non-shortened URLs, to avoid the chance of link-rot.  (This of course gives up goo.gl analytics).

I like the idea of godbolt.org sending a normal (non-API) request to the goo.gl server and capturing the 404 or 302 result.  That has the minimum number of network packets / connections / load on anyone's servers.  (I like efficiency in general, not just in assembly language :)  Or would the server process on godbolt.org keep a persistent connection open to a google API server?

Making it look like a proxied request from the client would require the CGI program to capture more headers from the client that it wouldn't normally care about.  I hadn't thought of that before.

For stackoverflow, this is hopefully just a stopgap for use in comments.  SO probably won't provide a workaround (like re-enabling shorteners in comments, or only for 50-rep users) before you can do this.  So for starters go with something that's easy to implement.

**Comment by mattgodbolt** [comment]
Thanks for the comprehensive reply @pcordes  :)

I've already submitted a change to make non-shortened links shorter and to be more human-readable. I haven't pushed that yet as I want a chance to test it. URLs now look of the form HOST/#compilers:!((compiler:g52,options:'-O3+-std%3Dc%2B%2B0x',source:'//+Hash+with+dynamic+number+of+buckets.%0Aextern+int+NumBuckets%3B%0Aint+hash1(int+value)+%7B%0A++++return+value+%25+NumBuckets%3B%0A%7D%0A%0A//+Hash+with+constant+number+of+buckets.%0Aconst+auto+ConstNumBuckets+%3D+257%3B%0Aint+hash2(int+value)+%7B%0A++++return+value+%25+ConstNumBuckets%3B%0A%7D%0A%0A//+Hash+with+constant+unsigned+number+of+buckets.+One%0A//+of+the+places+where+!'auto!'+might+have+led+to+a%0A//+problem+as+it!'s+easy+to+forget+the+trailing+!'u!'.%0Aconst+auto+uConstNumBuckets+%3D+257u%3B%0Aint+hash3(int+value)+%7B%0A++++return+value+%25+uConstNumBuckets%3B%0A%7D')),filterAsm:(colouriseAsm:!t,commentOnly:!t,directives:!t,intel:!t,labels:!t),version:3

...which is at least less scary-looking :)

I don't believe I can send a non-API request to goo.gl without risking being banned for misusing the service: I don't think this is something google like you doing in general. Most google services are smart enough to rate limit lots of requests coming from the same IP (as godbolt.org would appear); that's why the API service is there: to give accountability for server-side use of Google's services. I don't think the overhead would be that great either.

As for proxying the request; I don't think I'll be doing this at least for a first cut: again this falls foul of the "lots of requests apparently coming from one IP". As a proxy that's more understandable though. The simplicity of doing the redirect is appealing though.

I'll sketch something out and see how I feel once it's done! :)

**Comment by pcordes** [comment]
Yeah, I think I already mentioned that my idea of sending "proxied" non-API requests might run into rate-limiting.  It was the major thing that would need to be checked on.

re: new URL format: Maybe use shortnames like cc, opt, and src to save a few bytes, since it's a new format anyway?  Are you finding that URLencoding C/C++ source code tends to be shorter than whatever it was previously (BASE64?  gzip + BASE64?).  template-heavy C++ with a lot of angle brackets might come out worse. 

But this is probably a good change.  [Someone posted a question with JUST a godbolt link, and no code](http://meta.stackoverflow.com/questions/319549/how-are-we-supposed-to-post-godbolt-links-now-that-url-shortening-is-blocked?noredirect=1#comment326303_319549), and several people thought it looked sketchy.  Even if total idiots post just a godbolt.org link like that, it will be obvious at a glance to people that haven't heard of this site that there's source code encoded in it.

While you're changing things, it's probably a good idea to let the syntax include per-compiler options in the URL, to avoid needing another change later.  (It might be more confusing for someone to be sent a link and then switch compilers without realizing they were also changing options, though.  But leaving room for extensions without a version-bump will avoid having to maintain even more parsers.)

**Comment by mattgodbolt** [comment]
re: new URL format; I'll also be changing the objects it stores. Using cc opt/src etc would be great, but I don't want to make it /too/ awkward in the codebase with short names everywhere.  Previously I unconditionally b64-encoded a LZ-compressed string: now I use the plain text (URL encoded) unless the compressed version is more than 20% smaller. That's obviously up for comment!

When you say "let the syntax include per-compiler options in the URL" - what do you mean? The compiler options /are/ in the URL, and there's currently no support for per-compiler options: that's tracked in #98 and I haven't really thought of a way of handling that yet, from a UI point of view.

**Comment by pcordes** [comment]
I just meant to keep #98 in mind when designing the syntax.  That we might at some point in the future want the state to include a compiler->options map.  Every version number bump bloats the code-size in deserialiseState(), so making a future-proof format with room to grow is great.

re: 20% savings heuristic: that sounds reasonable.  Maybe even 30%.  URL encoded plain text is an advantage for posting link where people who are unfamiliar with this site will see them.  Once they're too long for mouseover to show the whole thing anyway, it doesn't really matter.  Having source-code-like stuff as close to the front of the URL as possible is good.

**Comment by mattgodbolt** [comment]
Thanks for clarifying! I'll see what I can do.

**Comment by pcordes** [comment]
I was still editing my last post when you replied, take a look again.  (I'll delete this post in a bit)

**Comment by mattgodbolt** [comment]
Thanks. Upper case doesn't help here, the URL "blob" decodes to a nice object that I use elsewhere in the code. That said, the deserialise/serialise code could be made to map names back and forth. The biggest issue is the filters: they're designed modularly and the names actually tally up with the names of the HTML elements in the page. I'd need another mapping table of "short name" to "name in HTML" and all that. Not impossible, of course: but taken in context when most of the length of the URL comes from the source code, perhaps not worth too much work. I'll definitely take a look though!

**Comment by pcordes** [comment]
Ok, thanks for the high-level summary of the motivation for naming.  My suggestion to map to/from short names in the URL was based on the assumption that it would be easy and not impact much code.  Given that the gain is tiny, not worth it unless you can find some middle ground with slightly shorter names that are still descriptive enough for var names.

**Comment by mattgodbolt** [comment]
Now live with https://godbolt.org/g/XYZABCD links.
