### ISSUE TITLE
GCC 5.2.0 fails to build with binary mode

### ISSUE THREAD

**Issue by mattgodbolt** [mattgodbolt/gcc-explorer#92]

**Comment by mattgodbolt** [comment]
Seems it sometimes misses the multiarch stuff (at least it did just now seemingly)

**Comment by pcordes** [comment]
It's usually only a problem with `-m32` or `-mx32`

I didn't realize this was compiler-dependent.  It turns out that your gcc 5.1.0 can build `-m32` binaries (http://goo.gl/ueH5tF), but no other compiler version will.

`g++-4.4: selected multilib '32' not installed`

gcc 4.5 to 4.9.2: some variation on
```
collect2: fatal error: cannot find 'ld'
compilation terminated.
Compilation failed
```

gcc 5 (other than 5.1): something like
```
/opt/gcc-5.2.0/bin/../lib/gcc/x86_64-linux-gnu/5.2.0/../../../../x86_64-linux-gnu/bin/ld: skipping incompatible /usr/lib/x86_64-linux-gnu/libc.so when searching for -lc
/opt/gcc-5.2.0/bin/../lib/gcc/x86_64-linux-gnu/5.2.0/../../../../x86_64-linux-gnu/bin/ld: skipping incompatible /usr/lib/x86_64-linux-gnu/libc.a when searching for -lc
/opt/gcc-5.2.0/bin/../lib/gcc/x86_64-linux-gnu/5.2.0/../../../../x86_64-linux-gnu/bin/ld: i386:x86-64 architecture of input file `/usr/lib/x86_64-linux-gnu/crt1.o' is incompatible with i386 output
/opt/gcc-5.2.0/bin/../lib/gcc/x86_64-linux-gnu/5.2.0/../../../../x86_64-linux-gnu/bin/ld: i386:x86-64 architecture of input file `/usr/lib/x86_64-linux-gnu/crti.o' is incompatible with i386 output
/opt/gcc-5.2.0/bin/../lib/gcc/x86_64-linux-gnu/5.2.0/../../../../x86_64-linux-gnu/bin/ld: i386:x86-64 architecture of input file `/usr/lib/x86_64-linux-gnu/crtn.o' is incompatible with i386 output
/opt/gcc-5.2.0/bin/../lib/gcc/x86_64-linux-gnu/5.2.0/../../../../x86_64-linux-gnu/bin/ld: /usr/lib/x86_64-linux-gnu/crt1.o: file class ELFCLASS64 incompatible with ELFCLASS32
/opt/gcc-5.2.0/bin/../lib/gcc/x86_64-linux-gnu/5.2.0/../../../../x86_64-linux-gnu/bin/ld: final link failed: File in wrong format
collect2: error: ld returned 1 exit status
```

clang: some variation on this, or can't find `-lstdc++` (even with `-xc`):
```
clang-3.7: error: unable to execute command: Executable "ld" doesn't exist!
clang-3.7: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by mattgodbolt** [comment]
I think this is now fixed as part of the big compiler clean-up I did. Almost all the GCCs now support m32 and binary mode. If there are any versions that you care about that don't, please re-open!

**Comment by pcordes** [comment]
Thanks for cleaning up the compilers, and having so many new and up-to-date gcc and clang options, and now some new Intel icc ones!

IDK if you want to add headers / libraries for the x32 ABI (ILP32 in long mode), but it's currently broken for compilers I tried (gcc6.2 and 5.4), even in non-binary mode depending on what headers you include (e.g. stddef.h is fine with -mx32, but stdio.h or atomic doesn't even compile: [... `fatal error: gnu/stubs-x32.h: No such file or directory`](http://gcc.godbolt.org/#g:!((g:!((g:!((h:codeEditor,i:(j:1,options:(colouriseAsm:'0',compileOnChange:'0'),source:'%23include+%3Catomic%3E++//+doesn!'t+compile+even+if+unused%0A//%23include+%3Cstdio.h%3E%0A%0A%23include+%3Cstddef.h%3E++//+works+even+for+-mx32%0A%0Aint+A%5B5%5D%5B5%5D%3B%0A%0Aint+foo(int+i,+int+j)%7B+%0A++return+A%5Bi%5D%5Bj%5D%3B%0A%7D%0A'),l:'5',n:'1',o:'C%2B%2B+source+%231',t:'0')),k:33.333333333333336,l:'4',n:'0',o:'',s:0,t:'0'),(g:!((h:compiler,i:(compiler:g62,filters:(b:'0',commentOnly:'0',directives:'0',intel:'0'),options:'-Og+-Wall+-Wextra+-mx32'),l:'5',n:'0',o:'%231+with+x86-64+gcc+6.2',t:'0')),k:33.333333333333336,l:'4',n:'0',o:'',s:0,t:'0'),(g:!((h:output,i:(compiler:1,editor:1),l:'5',n:'0',o:'%231+with+x86-64+gcc+6.2',t:'0')),k:33.33333333333333,l:'4',n:'0',o:'',s:0,t:'0')),l:'2',n:'0',o:'',t:'0')),version:4)

Having that working for the latest gcc5 and gcc6 might be nice.  BTW, there might be *too many* compilers now.  Perhaps some checkboxes to hide obscure stuff like multiple versions of gcc4.7 would be good.  It's a long scroll between gcc6 and clang.  I guess with multiple compiler tabs I should get used to using that instead of flipping one tab between compiler versions, which would make it less of an issue.

BTW, I really like the changes to the site layout. The new multi-pane setup that allows multiple compilers open at once is really cool!  It wasn't totally obvious that you can just drag a tab to get back to split-pane mode after closing all but the source tab, but I figured it out quickly.  Closing the compiler tab loses your compiler options, so I guess I just won't do that.

It's a huge improvement to readability with compile errors involving the wrong number of leading underscores, since you previous couldn't see underscores when the next line was solid-colour highlighted.   (Thanks Intel, I really love typing _mm256_redundant_name256.  pshufb256() would have been too easy.)

Getting rid of the diagonal github link that obscured the end of the compiler-options field is great.

**Comment by mattgodbolt** [comment]
Thanks for your comments! I'll take a look at the stubs-x32 stuff too.

FWIW the compiler box is searchable: you can type in the box and it'll autocomplete. Not sure that's much use, but it does help a little (I type 'ARM' or 'x86' for example to limit the dropdown to those compilers).

**Comment by pcordes** [comment]
> FWIW the compiler box is searchable

O.o, IDK if I ever would have discovered that.  It seems I have to clear the existing text (with ctrl-backspace or whatever) before anything even shows up when I type.  (Chromium 51).  But that does look useful, esp for getting to ARM.

Any chance of ARM and ARM64 gcc 6.2 or 5.4?  C11 stdatomic isn't supported by gcc4.8, although C++11 std::atomic is.  And I definitely remember wondering if newer ARM gcc would have made better code when 4.8 does something dumb.

**Comment by mattgodbolt** [comment]
@pcordes ARM and ARM64 5.4 are now up on the site. I can't find a pre-built ARM* GCC 6.2 anywhere; if there's one around (a la https://launchpad.net/gcc-arm-embedded ), I'd gladly add it

**Comment by mattgodbolt** [comment]
I _think_ this is now closed. Please comment if there's something I missed (I'm doing some cleaning up on the bug list).
